---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  product_name: chef
  solo_rb:
    treat_deprecation_warnings_as_errors: true

verifier:
  name: inspec

platforms:
  - name: amazonlinux-2
    driver_config:
      box: ywatase/amzn2
  - name: centos-7
  - name: debian-8
  - name: debian-9
  - name: fedora-28
  - name: opensuse-leap-42
  - name: ubuntu-16.04
  - name: ubuntu-18.04
  - name: centos-7-chef-13.3
    driver_config:
      box: bento/centos-7
    provisioner:
      require_chef_omnibus: 13.3
  - name: ubuntu-16.04-chef-13.3
    driver_config:
      box: bento/ubuntu-16.04
    provisioner:
      require_chef_omnibus: 13.3

suites:
  - name: distro
    run_list:
      - recipe[test::distro]
    excludes:
      - amazonlinux-2
      - centos-7
      - centos-7-chef-13.3
  - name: repo
    run_list:
      - recipe[test::repo]
    excludes:
      - fedora-28
      - centos-7-chef-13.3
      - ubuntu-16.04-chef-13.3

  - name: source
    run_list:
      - recipe[test::source]
  - name: epel
    run_list:
      - recipe[test::epel]
    includes:
      - amazonlinux-2
      - centos-7
  - name: source
    run_list:
      - recipe[test::source]
  - name: modules
    run_list:
      - recipe[test::modules]
    excludes:
      - centos-7-chef-13.3
      - ubuntu-16.04-chef-13.3
  - name: passenger
    run_list:
      - recipe[test::passenger_packages]
    excludes:  # passenger distro install is not compatible with these
      - amazonlinux-2
      - centos-7-chef-13.3
      - ubuntu-16.04-chef-13.3
      - opensuse-leap-42
      - centos-7
      - fedora-28
  - name: stream
    run_list:
      - recipe[test::stream]
